### ISSUE TITLE
[RFF]: Single Component Display

### ISSUE THREAD

**Issue by FabDonRixos** [FabDonRixos/awesome-arts#11]
### Is your feature request related to a problem?

The Description of the Component isn't displayed.

### Describe the solution you'd like.

I would like to have a way of klicking a component inside the list. When i click the component it should open up somehow and it should ony show this Component with some aditional infos for example the description.

### Additional information's

 And maby in the future we can display more information there or expand the features of the single display.
You can use react router but I think it would be easier to just remove the list from the dome and display only the component.

### TODO's

- [X] The feature hasn't been requested yet.
- [X] The title is clear and descriptive.
- [X] The feature is properly described.
- [X] The Feature has good tags.
- [ ] The issue is assigned to the correct person (if necessary)

### Code of Conduct

- [X] I agree to follow the Code of Conduct
