### ISSUE TITLE
[CW]: Yin Yang

### ISSUE THREAD

**Issue by FabDonRixos** [FabDonRixos/awesome-arts#37]
### Category

Shapes

### Description

A Ying Yang which rotates when clicked on. And maybe some other details.
[attributes](https://i.pinimg.com/736x/62/91/17/629117bcc2b797f8d96de2dee8e943de.jpg)

### TODO's

- [X] The component hasn't been suggested / isn't already implemented yet.
- [X] The title is clear and descriptive.
- [X] The component is properly described.
- [X] Your name is under Assignees
- [X] The Component has good tags.

### Code of Conduct

- [X] I agree to follow the Code of Conduct
