### ISSUE TITLE
[CW]: Snow Globe

### ISSUE THREAD

**Issue by FabDonRixos** [FabDonRixos/awesome-arts#38]
### Category

Holidays

### Inspiration

Winter

### Description

A snow globe that has some kind of Christmas motif (not quite sure yet) inside and the is snow falling as you know it from a snow globe

### TODO's

- [X] The component hasn't been suggested / isn't already implemented yet.
- [X] The title is clear and descriptive.
- [X] The component is properly described.
- [X] Your name is under Assignees
- [X] The Component has good tags.

### Code of Conduct

- [X] I agree to follow the Code of Conduct
